package com.github.exact7.xtra.util

object C {
    const val USER_PREFS = "userPrefs"
    const val STREAM = "stream"
    const val VIDEO = "video"
    const val CLIP = "clip"
    const val GAME = "game"
    const val TOKEN = "token"
    const val USER = "user"
    const val USERNAME = "username"
    const val USER_ID = "user_id"
    const val FIRST_LAUNCH = "first_launch"
    const val CHANNEL = "channel"
    const val THEME = "theme"
    const val PORTRAIT_PLAYER_HEIGHT  = "portrait_player_height"
    const val LANDSCAPE_CHAT_WIDTH = "landscape_chat_width"
    const val PORTRAIT_COLUMN_COUNT = "columnsPortrait"
    const val LANDSCAPE_COLUMN_COUNT = "columnsLandscape"
    const val DOWNLOAD_STORAGE = "downloadStorage"
    const val PICTURE_IN_PICTURE = "pictureInPicture"
    const val ASPECT_RATIO_PORTRAIT = "aspectRatioPortrait"
    const val ASPECT_RATIO_LANDSCAPE = "aspectRatioLandscape"
    const val DOWNLOAD_NETWORK_PREFERENCE = "downloadNetworkPreference"
}